# Generated by Django 3.2.6 on 2021-08-13 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myclientapp_shared', '0001_initial'),
        ('myclientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sweet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myclientapp_shared.sweettype')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
